apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: cage
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "mongodb.cage.svc.cluster.local:27017"
  - name: databaseName
    value: "DaprSagaDB"
  - name: collectionName
    value: "sagaStates"
