apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: cage
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: rabbitmq-secret
      key: connectionString
  - name: durable
    value: "true"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: deliveryMode
    value: "2"
  - name: requeueInFailure
    value: "true"
