apiVersion: v1
kind: Secret
metadata:
  name: cage-secrets
  namespace: cage
type: Opaque
stringData:
  # RabbitMQ
  rabbitmq-connection-string: "amqp://guest:guest@rabbitmq.cage.svc.cluster.local:5672"
  
  # MongoDB
  mongodb-password: "dvpq25AxXzDsCMqAv5cF"
  mongodb-connection-string: "mongodb://cage:dvpq25AxXzDsCMqAv5cF@172.19.201.142:30017/cage"
  
  # Nacos
  nacos-password: "nacos"
